
FROM httpd
COPY ./hospital-website-template/* /usr/local/apache2/htdocs/

# Notes
# Docker version 20.10.17, build 100c701
# docker stop my-running-app; docker rm my-running-app
# Trouble-shooting https://github.com/GoogleContainerTools/container-diff
# sudo docker commit [CONTAINER_ID] [new_image_name]
# docker cp /root/build/con/. 22a395a89257:/usr/local/apache2/htdocs/